In [1]:
import pandas as pd
train_labels = pd.read_csv('Archivos de datos/train_labels.csv', encoding='latin-1')
train_values = pd.read_csv('Archivos de datos/train_values.csv', encoding='latin-1')

In [2]:
train_labels.head()

   building_id  damage_grade
0       802906             3
1        28830             2
2        94947             3
3       590882             2
4       201944             3

In [3]:
train_values.head()

,building_id,geo_level_1_id,geo_level_2_id,geo_level_3_id,count_floors_pre_eq,age,area_percentage,height_percentage,land_surface_condition,foundation_type,...,has_secondary_use_agriculture,has_secondary_use_hotel,has_secondary_use_rental,has_secondary_use_institution,has_secondary_use_school,has_secondary_use_industry,has_secondary_use_health_post,has_secondary_use_gov_office,has_secondary_use_use_police,has_secondary_use_other
0,802906,6,487,12198,2,30,6,5,t,r,...,0,0,0,0,0,0,0,0,0,0
1,28830,8,900,2812,2,10,8,7,o,r,...,0,0,0,0,0,0,0,0,0,0
2,94947,21,363,8973,2,10,5,5,t,r,...,0,0,0,0,0,0,0,0,0,0
3,590882,22,418,10694,2,10,6,5,t,r,...,0,0,0,0,0,0,0,0,0,0
4,201944,11,131,1488,3,30,8,9,t,r,...,0,0,0,0,0,0,0,0,0,0

En el Tp1 corroboramos que ambos dataset no tenian valores nulos

In [4]:
train_values.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260601 entries, 0 to 260600
Data columns (total 39 columns):
 #   Column                                  Non-Null Count   Dtype
---  ------                                  --------------   -----
 0   building_id                             260601 non-null  int64
 1   geo_level_1_id                          260601 non-null  int64
 2   geo_level_2_id                          260601 non-null  int64
 3   geo_level_3_id                          260601 non-null  int64
 4   count_floors_pre_eq                     260601 non-null  int64
 5   age                                     260601 non-null  int64
 6   area_percentage                         260601 non-null  int64
 7   height_percentage                       260601 non-null  int64
 8   land_surface_condition                  260601 non-null  object
 9   foundation_type                         260601 non-null  object
 10  roof_type                               260601 non-null  object
 11  ground_floor_type                       260601 non-null  object
 12  other_floor_type                        260601 non-null  object
 13  position                                260601 non-null  object
 14  plan_configuration                      260601 non-null  object
 15  has_superstructure_adobe_mud            260601 non-null  int64
 16  has_superstructure_mud_mortar_stone     260601 non-null  int64
 17  has_superstructure_stone_flag           260601 non-null  int64
 18  has_superstructure_cement_mortar_stone  260601 non-null  int64
 19  has_superstructure_mud_mortar_brick     260601 non-null  int64
 20  has_superstructure_cement_mortar_brick  260601 non-null  int64
 21  has_superstructure_timber               260601 non-null  int64
 22  has_superstructure_bamboo               260601 non-null  int64
 23  has_superstructure_rc_non_engineered    260601 non-null  int64
 24  has_superstructure_rc_engineered        260601 non-null  int64
 25  has_superstructure_other                260601 non-null  int64
 26  legal_ownership_status                  260601 non-null  object
 27  count_families                          260601 non-null  int64
 28  has_secondary_use                       260601 non-null  int64
 29  has_secondary_use_agriculture           260601 non-null  int64
 30  has_secondary_use_hotel                 260601 non-null  int64
 31  has_secondary_use_rental                260601 non-null  int64
 32  has_secondary_use_institution           260601 non-null  int64
 33  has_secondary_use_school                260601 non-null  int64
 34  has_secondary_use_industry              260601 non-null  int64
 35  has_secondary_use_health_post           260601 non-null  int64
 36  has_secondary_use_gov_office            260601 non-null  int64
 37  has_secondary_use_use_police            260601 non-null  int64
 38  has_secondary_use_other                 260601 non-null  int64
dtypes: int64(31), object(8)
memory usage: 77.5+ MB

Me transformo las columnas tipo object en categoricos

In [5]:
train_values = train_values.astype({'land_surface_condition':'category', 'foundation_type':'category',\
                                    'roof_type':'category', 'ground_floor_type':'category',\
                                    'other_floor_type':'category', 'position':'category',\
                                    'plan_configuration':'category', 'legal_ownership_status':'category'
                                    })

In [6]:
train_values.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260601 entries, 0 to 260600
Data columns (total 39 columns):
 #   Column                                  Non-Null Count   Dtype
---  ------                                  --------------   -----
 0   building_id                             260601 non-null  int64
 1   geo_level_1_id                          260601 non-null  int64
 2   geo_level_2_id                          260601 non-null  int64
 3   geo_level_3_id                          260601 non-null  int64
 4   count_floors_pre_eq                     260601 non-null  int64
 5   age                                     260601 non-null  int64
 6   area_percentage                         260601 non-null  int64
 7   height_percentage                       260601 non-null  int64
 8   land_surface_condition                  260601 non-null  category
 9   foundation_type                         260601 non-null  category
 10  roof_type                               260601 non-null  category
 11  ground_floor_type                       260601 non-null  category
 12  other_floor_type                        260601 non-null  category
 13  position                                260601 non-null  category
 14  plan_configuration                      260601 non-null  category
 15  has_superstructure_adobe_mud            260601 non-null  int64
 16  has_superstructure_mud_mortar_stone     260601 non-null  int64
 17  has_superstructure_stone_flag           260601 non-null  int64
 18  has_superstructure_cement_mortar_stone  260601 non-null  int64
 19  has_superstructure_mud_mortar_brick     260601 non-null  int64
 20  has_superstructure_cement_mortar_brick  260601 non-null  int64
 21  has_superstructure_timber               260601 non-null  int64
 22  has_superstructure_bamboo               260601 non-null  int64
 23  has_superstructure_rc_non_engineered    260601 non-null  int64
 24  has_superstructure_rc_engineered        260601 non-null  int64
 25  has_superstructure_other                260601 non-null  int64
 26  legal_ownership_status                  260601 non-null  category
 27  count_families                          260601 non-null  int64
 28  has_secondary_use                       260601 non-null  int64
 29  has_secondary_use_agriculture           260601 non-null  int64
 30  has_secondary_use_hotel                 260601 non-null  int64
 31  has_secondary_use_rental                260601 non-null  int64
 32  has_secondary_use_institution           260601 non-null  int64
 33  has_secondary_use_school                260601 non-null  int64
 34  has_secondary_use_industry              260601 non-null  int64
 35  has_secondary_use_health_post           260601 non-null  int64
 36  has_secondary_use_gov_office            260601 non-null  int64
 37  has_secondary_use_use_police            260601 non-null  int64
 38  has_secondary_use_other                 260601 non-null  int64
dtypes: category(8), int64(31)
memory usage: 63.6 MB

In [8]:
#Aplicamos get_dummies para librarnos de los categoricos con los que los modelos pudieran tener problemas
x = pd.get_dummies(train_values)

In [9]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260601 entries, 0 to 260600
Data columns (total 69 columns):
 #   Column                                  Non-Null Count   Dtype
---  ------                                  --------------   -----
 0   building_id                             260601 non-null  int64
 1   geo_level_1_id                          260601 non-null  int64
 2   geo_level_2_id                          260601 non-null  int64
 3   geo_level_3_id                          260601 non-null  int64
 4   count_floors_pre_eq                     260601 non-null  int64
 5   age                                     260601 non-null  int64
 6   area_percentage                         260601 non-null  int64
 7   height_percentage                       260601 non-null  int64
 8   has_superstructure_adobe_mud            260601 non-null  int64
 9   has_superstructure_mud_mortar_stone     260601 non-null  int64
 10  has_superstructure_stone_flag           260601 non-null  int64
 11  has_superstructure_cement_mortar_stone  260601 non-null  int64
 12  has_superstructure_mud_mortar_brick     260601 non-null  int64
 13  has_superstructure_cement_mortar_brick  260601 non-null  int64
 14  has_superstructure_timber               260601 non-null  int64
 15  has_superstructure_bamboo               260601 non-null  int64
 16  has_superstructure_rc_non_engineered    260601 non-null  int64
 17  has_superstructure_rc_engineered        260601 non-null  int64
 18  has_superstructure_other                260601 non-null  int64
 19  count_families                          260601 non-null  int64
 20  has_secondary_use                       260601 non-null  int64
 21  has_secondary_use_agriculture           260601 non-null  int64
 22  has_secondary_use_hotel                 260601 non-null  int64
 23  has_secondary_use_rental                260601 non-null  int64
 24  has_secondary_use_institution           260601 non-null  int64
 25  has_secondary_use_school                260601 non-null  int64
 26  has_secondary_use_industry              260601 non-null  int64
 27  has_secondary_use_health_post           260601 non-null  int64
 28  has_secondary_use_gov_office            260601 non-null  int64
 29  has_secondary_use_use_police            260601 non-null  int64
 30  has_secondary_use_other                 260601 non-null  int64
 31  land_surface_condition_n                260601 non-null  uint8
 32  land_surface_condition_o                260601 non-null  uint8
 33  land_surface_condition_t                260601 non-null  uint8
 34  foundation_type_h                       260601 non-null  uint8
 35  foundation_type_i                       260601 non-null  uint8
 36  foundation_type_r                       260601 non-null  uint8
 37  foundation_type_u                       260601 non-null  uint8
 38  foundation_type_w                       260601 non-null  uint8
 39  roof_type_n                             260601 non-null  uint8
 40  roof_type_q                             260601 non-null  uint8
 41  roof_type_x                             260601 non-null  uint8
 42  ground_floor_type_f                     260601 non-null  uint8
 43  ground_floor_type_m                     260601 non-null  uint8
 44  ground_floor_type_v                     260601 non-null  uint8
 45  ground_floor_type_x                     260601 non-null  uint8
 46  ground_floor_type_z                     260601 non-null  uint8
 47  other_floor_type_j                      260601 non-null  uint8
 48  other_floor_type_q                      260601 non-null  uint8
 49  other_floor_type_s                      260601 non-null  uint8
 50  other_floor_type_x                      260601 non-null  uint8
 51  position_j                              260601 non-null  uint8
 52  position_o                              260601 non-null  uint8
 53  position_s                              260601 non-null  uint8
 54  position_t                              260601 non-null  uint8
 55  plan_configuration_a                    260601 non-null  uint8
 56  plan_configuration_c                    260601 non-null  uint8
 57  plan_configuration_d                    260601 non-null  uint8
 58  plan_configuration_f                    260601 non-null  uint8
 59  plan_configuration_m                    260601 non-null  uint8
 60  plan_configuration_n                    260601 non-null  uint8
 61  plan_configuration_o                    260601 non-null  uint8
 62  plan_configuration_q                    260601 non-null  uint8
 63  plan_configuration_s                    260601 non-null  uint8
 64  plan_configuration_u                    260601 non-null  uint8
 65  legal_ownership_status_a                260601 non-null  uint8
 66  legal_ownership_status_r                260601 non-null  uint8
 67  legal_ownership_status_v                260601 non-null  uint8
 68  legal_ownership_status_w                260601 non-null  uint8
dtypes: int64(31), uint8(38)
memory usage: 71.1 MB

In [10]:
x.to_csv('Archivos de datos/datos_procesados.csv',index=False)

Tambien transformo los 'Object' del test_values a 'Categoricos'

In [11]:
values=pd.read_csv('Archivos de datos/test_values.csv')
values.to_csv('Archivos de datos/test_values_original.csv',index=False)
values = values.astype({'land_surface_condition':'category', 'foundation_type':'category',\
                                    'roof_type':'category', 'ground_floor_type':'category',\
                                    'other_floor_type':'category', 'position':'category',\
                                    'plan_configuration':'category', 'legal_ownership_status':'category'
                                    })
values.to_csv('Archivos de datos/test_values.csv',index=False)

In [12]:
values.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 86868 entries, 0 to 86867
Data columns (total 39 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   building_id                             86868 non-null  int64
 1   geo_level_1_id                          86868 non-null  int64
 2   geo_level_2_id                          86868 non-null  int64
 3   geo_level_3_id                          86868 non-null  int64
 4   count_floors_pre_eq                     86868 non-null  int64
 5   age                                     86868 non-null  int64
 6   area_percentage                         86868 non-null  int64
 7   height_percentage                       86868 non-null  int64
 8   land_surface_condition                  86868 non-null  category
 9   foundation_type                         86868 non-null  category
 10  roof_type                               86868 non-null  category
 11  ground_floor_type                       86868 non-null  category
 12  other_floor_type                        86868 non-null  category
 13  position                                86868 non-null  category
 14  plan_configuration                      86868 non-null  category
 15  has_superstructure_adobe_mud            86868 non-null  int64
 16  has_superstructure_mud_mortar_stone     86868 non-null  int64
 17  has_superstructure_stone_flag           86868 non-null  int64
 18  has_superstructure_cement_mortar_stone  86868 non-null  int64
 19  has_superstructure_mud_mortar_brick     86868 non-null  int64
 20  has_superstructure_cement_mortar_brick  86868 non-null  int64
 21  has_superstructure_timber               86868 non-null  int64
 22  has_superstructure_bamboo               86868 non-null  int64
 23  has_superstructure_rc_non_engineered    86868 non-null  int64
 24  has_superstructure_rc_engineered        86868 non-null  int64
 25  has_superstructure_other                86868 non-null  int64
 26  legal_ownership_status                  86868 non-null  category
 27  count_families                          86868 non-null  int64
 28  has_secondary_use                       86868 non-null  int64
 29  has_secondary_use_agriculture           86868 non-null  int64
 30  has_secondary_use_hotel                 86868 non-null  int64
 31  has_secondary_use_rental                86868 non-null  int64
 32  has_secondary_use_institution           86868 non-null  int64
 33  has_secondary_use_school                86868 non-null  int64
 34  has_secondary_use_industry              86868 non-null  int64
 35  has_secondary_use_health_post           86868 non-null  int64
 36  has_secondary_use_gov_office            86868 non-null  int64
 37  has_secondary_use_use_police            86868 non-null  int64
 38  has_secondary_use_other                 86868 non-null  int64
dtypes: category(8), int64(31)
memory usage: 21.2 MB